frontend:
	@echo Installing Frontend
catalogue:
	@echo Installing catalogue
cart:
	@echo Installing cart
user:
	@echo Installing User
shipping:
	@echo Installing shipping
payment:
	@echo Installing payment
mongodb:
	@echo Installing mongodb
redis:
	@echo Installing redis
mysql:
	@echo Installing MYSQL
rabbitmq:
	@echo Installing RabbitMQ

