help:		## Print this message
	@fgrep -h "##" $(MAKEFILE_LIST) | fgrep -v fgrep | sed -e 's/\\$$//' | sed -e 's/##//'
frontend:	## installing Frontend Component
	@echo Installing Frontend
catalogue:	## installing Catalogue Component
	@echo Installing Catalogue
cart:		## installing Cart Component
	@echo Installing Cart
user:		## installing User Component
	@echo Installing User
shipping:	## installing Shipping Component
	@echo Installing Shipping
payment:	## installing Payment Component
	@echo Installing Payment
mongodb:	## installing MOngoDB Component
	@echo Installing MongoDB
redis:		## installing Redis Component
	@echo Installing Redis
mysql:		## installing MySQL Component
	@echo Installing MySQL
rabbitmq:	## installing RabbitMQ Component
	@echo Installing RabbitMQ

